from scengine.vector2 import Vector2

vec = Vector2

render_distance_matrices = {
    "diamond": [
        [
            vec(0, 0),
            vec(1, 0),
            vec(0, 1),
            vec(-1, 0),
            vec(0, -1),
        ],
        [
            vec(0, 2),
            vec(1, 1),
            vec(2, 0),
            vec(1, -1),
            vec(0, -2),
            vec(-1, -1),
            vec(-2, 0),
            vec(-1, 1),
        ],
        [
            vec(0, 3),
            vec(1, 2),
            vec(2, 1),
            vec(3, 0),
            vec(2, -1),
            vec(1, -2),
            vec(0, -3),
            vec(-1, -2),
            vec(-2, -1),
            vec(-3, 0),
            vec(-2, 1),
            vec(-1, 2),
        ],
    ],
    "square": [
        [
            vec(0, 0),
            vec(0, 1),
            vec(1, 1),
            vec(1, 0),
            vec(1, -1),
            vec(0, -1),
            vec(-1, -1),
            vec(-1, 0),
            vec(-1, 1),
        ],
        [
            vec(0, 2),
            vec(1, 2),
            vec(2, 2),
            vec(2, 1),
            vec(2, 0),
            vec(2, -1),
            vec(2, -2),
            vec(1, -2),
            vec(0, -2),
            vec(-1, -2),
            vec(-2, -2),
            vec(-2, -1),
            vec(-2, 0),
            vec(-2, 1),
            vec(-2, 2),
            vec(-1, 2),
        ],
    ],
}
