video:
    framerate: 60
    vsync: true
    size:
        width: 1280
        height: 720
    resolution:
        width: 480
        height: 270
    camera_scroll_smoothness: 12

keybinds:
    left: q
    right: d
    up: z
    down: s
