video:
    framerate: 420
    vsync: false
    size:
        width: 1280
        height: 720
    resolution:
        # width: 640
        # height: 360
        width: 2560
        height: 1440
    camera_scroll_smoothness: 12

keybinds:
    left: q
    right: d
    up: z
    down: s
    sprint: a
