video:
    framerate: 420
    vsync: false
    size:
        width: 1280
        height: 720
    resolution:
        width: 1280
        height: 720
    camera_scroll_smoothness: 12

keybinds:
    left: q
    right: d
    up: z
    down: s
